const ToninhoTornadoApelidos = [
  "Mussarelo",
  "Calabreso",
  "Delício",
  "Samsungo",
  "Mato Atlântico",
  "Rito Cadillaco",
  "Casos Bahio",
  "Silos Malafaio",
  "Patricio Poeto",
  "Valesco Popozudo",
  "Arábio Saudito",
  "Magazino Luizo",
  "Iphono",
  "Caldo de Cano",
  "Sapopembo",
  "Iveto Sangalo",
  "Inseticido",
  "Madonno",
  "Princeso",
  "Panqueco",
  "Salado de Fruto",
  "Virílio",
  "Cracolândio",
  "Cervejo",
  "Borboleto",
  "Cadelo",
  "Lasanho",
  "Frigideiro",
  "Hemorróido",
  "Lapiseiro",
  "Amoxilino",
  "Carniço",
  "Geladeiro",
  "Tutti-fruto",
  "Menstruado",
  "Prechéco",
  "Lantejolo",
  "Camisinho",
  "Bisteco",
  "Aeromoço",
  "Lagartixo",
  "Dipirono",
  "Zebro",
  "Mortadelo",
  "Capivaro",
  "Cibaleno",
  "Salsicho",
  "Tilápio",
  "Lombrigo",
  "Perereco",
  "Monaliso",
  "Calopsito",
  "Carambolo",
  "Lesmo",
  "Pastilho",
  "Chavasco",
  "Perébo",
  "Chupeto",
  "Fanto Laranjo",
  "Sandálio",
  "Seborréio",
  "Pitango",
  "Sonho de Valso",
  "Macaxero",
  "Jiboio",
  "Cenouro",
  "Corvino",
  "Toscano",
  "Alfaço",
  "Cerejo",
  "Margarido",
  "Gasolino",
  "Donzelo",
  "Tadalafilo",
  "Menopauso",
  "Xilocaíno",
  "Mamadeiro",
  "Abelho",
  "Testosterono",
  "Lacraio",
  "Saboneto",
  "Tubaíno",
  "Shakiro",
  "Ludmilo",
  "Cláudia Raio",
  "Anito",
  "Caraguatatubo",
  "Araraquaro",
  "Ubatubo",
  "Braganço Paulisto",
];

function getRandomToninhoTornadoApelido(): string {
  return ToninhoTornadoApelidos[
    Math.floor(Math.random() * ToninhoTornadoApelidos.length)
  ];
}

export const Memes = { getRandomToninhoTornadoApelido };
